global:
  scrape_interval: "10s"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: "node01"
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: "pc"
    static_configs:
      - targets:
          - 192.168.1.100:9100